# Generated by Django 3.0 on 2024-02-09 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknow',
            name='name',
        ),
        migrations.AddField(
            model_name='booknow',
            name='car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.Car'),
        ),
    ]
